version: 2

updates:
   -  package-ecosystem: github-actions
      directory: /
      schedule:
         interval: monthly
      open-pull-requests-limit: 5
      commit-message:
         prefix: chore(ci)
         include: scope
      groups:
         github-actions:
            patterns:
               - "*"

   -  package-ecosystem: gradle
      directory: /android
      schedule:
         interval: monthly
      open-pull-requests-limit: 5
      commit-message:
         prefix: chore(android)
         include: scope
      groups:
         android-dependencies:
            patterns:
               - "*"

   -  package-ecosystem: gradle
      directory: /backend
      schedule:
         interval: monthly
      open-pull-requests-limit: 5
      commit-message:
         prefix: chore(backend)
         include: scope
      groups:
         backend-dependencies:
            patterns:
               - "*"

   -  package-ecosystem: gradle
      directory: /shared
      schedule:
         interval: monthly
      open-pull-requests-limit: 5
      commit-message:
         prefix: chore(shared)
         include: scope
      groups:
         shared-dependencies:
            patterns:
               - "*"

   -  package-ecosystem: docker
      directory: /deploy
      schedule:
         interval: weekly
         day: monday
      open-pull-requests-limit: 3
      commit-message:
         prefix: chore(docker)
         include: scope
      groups:
         docker-dependencies:
            patterns:
               - "*"
